version: '3.3'
services:
  post_db:
    image: mongo:3.2
    volumes:
      - post_db:/data/db
    networks:
      back:
        aliases:
          - post_db
          - posts
  ui:
    build: ./ui
    image: ${UserName}/ui:1.0
    ports:
      - ${PUBLIC_PORT}/tcp
    networks:
      front:
        aliases:
          - ui
  post:
    build: ./post-py
    image: ${UserName}/post:1.0
    networks:
      back:
        aliases:
          - post
      front:
        aliases:
          - post
  comment:
    build: ./comment
    image: ${UserName}/comment:1.0
    networks:
      back:
        aliases:
          - comment
      front:
        aliases:
          - comment
  prometheus:
    image: gbutyaev/prometheus
    ports:
      - '9090:9090'
    volumes:
      - prometheus_data:/prometheus
    command: #передаем доп параметры в командной строке
      - '--config.file=/etc/prometheus/prometheus.yml'
      - '--storage.tsdb.path=/prometheus'
      - '--storage.tsdb.retention=1d' #задаем время хранение метрик в один день
    networks:
      - front
      - back


volumes:
  post_db:
  prometheus_data:

networks:
  back:
    external:
      name: back_net
  front:
    external:
      name: front_net
